# Generated by Django 5.2.16 on 2026-07-12 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Product Name')),
                ('sku', models.CharField(max_length=50, unique=True, verbose_name='SKU/Barcode')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price (INR)')),
                ('stock', models.IntegerField(default=0, verbose_name='Current Stock')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
