# Generated by Django 5.2.16 on 2026-07-23 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='last_moment_discount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Checkout par surprise discount dene ke liye amount set karein', max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='mrp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
