# Generated by Django 5.2.16 on 2026-07-23 11:08

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_product_last_moment_discount_product_mrp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='animated_file',
            field=models.FileField(blank=True, help_text='Upload GIF or animated video', null=True, storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(), upload_to='banners/'),
        ),
    ]
