# Generated by Django 5.2.16 on 2026-07-23 11:18

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_alter_banner_animated_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='image',
            field=models.ImageField(blank=True, help_text='Sirf Image yahan upload karein (PNG/JPG)', null=True, upload_to='banners/'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='animated_file',
            field=models.FileField(blank=True, help_text='Sirf Video yahan upload karein (MP4)', null=True, storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(), upload_to='banners/videos/'),
        ),
    ]
