# Generated by Django 5.2.16 on 2026-07-26 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_remove_coupon_is_used_remove_coupon_mobile_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Chachan General Store', max_length=255)),
                ('tagline', models.CharField(default='Premium Corporate Retail & Essentials', max_length=255)),
                ('store_address', models.TextField(blank=True, help_text='Full address to print on Bill of Supply', null=True)),
                ('store_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('gstin', models.CharField(blank=True, help_text='GST Number', max_length=50, null=True)),
            ],
        ),
    ]
