# Generated by Django 5.2.16 on 2026-08-04 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_product_color_product_size_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='review_pics/'),
        ),
    ]
