# Generated by Django 5.2.16 on 2026-08-05 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_review_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='banner',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Agar select karein, to banner click karne par is category ke products dikhenge', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banners', to='products.category'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Out for Delivery', 'Out for Delivery'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], db_index=True, default='Pending', max_length=50),
        ),
    ]
