# Generated by Django 5.2.16 on 2026-08-05 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0029_alter_order_options_banner_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storesetting',
            old_name='store_phone',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='storesetting',
            old_name='company_name',
            new_name='store_name',
        ),
        migrations.RemoveField(
            model_name='storesetting',
            name='store_address',
        ),
        migrations.AddField(
            model_name='storesetting',
            name='address',
            field=models.TextField(blank=True, default='Nohar, Rajasthan', null=True),
        ),
        migrations.AddField(
            model_name='storesetting',
            name='owner_name',
            field=models.CharField(blank=True, default='Proprietor', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='storesetting',
            name='receipt_footer',
            field=models.CharField(default='Thank you, please visit again!', max_length=255),
        ),
        migrations.AlterField(
            model_name='storesetting',
            name='tagline',
            field=models.CharField(blank=True, default='Premium Corporate Retail & Essentials', max_length=255, null=True),
        ),
    ]
