# Generated by Django 5.2.16 on 2026-08-05 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0032_customerledger'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceablePincode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pincode', models.CharField(db_index=True, max_length=6, unique=True)),
                ('city_name', models.CharField(max_length=100)),
                ('branch_name', models.CharField(default='Nohar Main Hub', max_length=100)),
                ('is_serviceable', models.BooleanField(default=True)),
                ('delivery_estimate', models.CharField(default='24-48 Hours', max_length=100)),
                ('shipping_charge', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
            ],
        ),
    ]
