# Generated by Django 5.2.16 on 2026-08-05 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0033_serviceablepincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceablepincode',
            name='delivery_estimate',
            field=models.CharField(default='10 Mins - 1 Hour', max_length=100),
        ),
    ]
