# Generated by Django 5.2.16 on 2026-08-05 15:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0036_expense_supplier_supplierledger'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryBoy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(max_length=15, unique=True)),
                ('vehicle_number', models.CharField(blank=True, help_text='Bike ya Gaadi ka number', max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Agar staff chhutti par hai toh isko untick karein')),
                ('joined_date', models.DateField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_boy',
            field=models.ForeignKey(blank=True, help_text='Is order ko kaun deliver karega?', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_orders', to='products.deliveryboy'),
        ),
    ]
