# Generated by Django 5.2.16 on 2026-08-06 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0039_order_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='last_otp_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_mode',
            field=models.CharField(default='Cash on Delivery (COD)', max_length=50),
        ),
    ]
